### ISSUE TITLE
Crash while using bluetooth controller

### ISSUE THREAD

**Issue by SamBeastie** [tkashkin/GameHub#393]
###### Steps to reproduce
Launch GameHub, try to move selection with controller

###### Version and environment

```- GameHub
    Version: 0.16.0-a5cc00c-makepkg
    Branch:  makepkg
    Commit:  a5cc00cc57750f7063d004b92ef39d2bb5f5ddec
- Environment
    Distro:  Arch Linux
    DE:      GNOME
    GTK:     3.24.20
    Themes:  Arc-Darker | Numix-Circle
```

###### GDB log

<details>
<summary>GDB log</summary>

```
[DEBUG]  [Database.migrate] Latest db version: 11, current: 11
[INFO]   - GameHub
[INFO]       Version: 0.16.0-a5cc00c-makepkg
[INFO]       Branch:  makepkg
[INFO]       Commit:  a5cc00cc57750f7063d004b92ef39d2bb5f5ddec
[INFO]   - Environment
[INFO]       Distro:  Arch Linux
[INFO]       DE:      GNOME
[INFO]       GTK:     3.24.20
[INFO]       Themes:  Arc-Darker | Numix-Circle
[DEBUG]  [Gamepad] '8Bitdo SF30 Pro' connected
[DEBUG]  [Gamepad] 'Microsoft X-Box 360 pad' connected
[INFO]   [ButlerClient: log] Fetching fresh data...
[INFO]   [ButlerClient: log] Fetching page 1
[INFO]   [ButlerClient: log] Fetching page 2
[INFO]   [ButlerClient: log] Waited 53.913626ms for fetch (non-shared)
[DEBUG]  [GOG] Loading games: page 1 of 1
[DEBUG]  [Merge] Merging Steam games
[DEBUG]  [Merge] Merging GOG games
[DEBUG]  [Merge] Merging Humble Bundle games
[DEBUG]  [Merge] Merging Humble Trove games
[DEBUG]  [Merge] Merging itch.io games
[DEBUG]  [Merge] Merging User games games
[FATAL]  [Gdk] gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

Thread 1 "com.github.tkas" received signal SIGSEGV, Segmentation fault.
0x00007ffff38956aa in XKeysymToKeycode () from /usr/lib/libX11.so.6

Thread 14 (Thread 0x7fffc67fc700 (LWP 33139)):
#0  0x00007ffff373071d in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff7c207ab in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7ba8803 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7ba8994 in g_async_queue_timeout_pop () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7c04caa in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7c00511 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff3207422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff3735bf3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffdffff700 (LWP 33100)):
#0  0x00007ffff372b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c25f38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bd7221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7f97e5e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff7c00511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3207422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3735bf3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffecb6c700 (LWP 33099)):
#0  0x00007ffff36fd571 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007ffff3702e87 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7bfdf31 in g_usleep () at /usr/lib/libglib-2.0.so.0
#3  0x00005555556a7913 in __lambda395_ (self=0x555565c68370) at ../src/ui/views/GamesView/GamesView.vala:919
#4  0x00005555556a7958 in ___lambda395__game_hub_utils_future (self=0x555565c68370) at ../src/ui/views/GamesView/GamesView.vala:911
#5  0x000055555571127d in game_hub_utils_worker_run (self=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
) at ../src/utils/Utils.vala:47
#6  0x0000555555717578 in ____lambda7_ (w=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
) at ../src/utils/Utils.vala:328
#7  0x00005555557175b1 in _____lambda7__gfunc (data=0x555565fcd380, self=0x0) at ../src/utils/Utils.vala:328
#8  0x00007ffff7c04c07 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7c00511 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff3207422 in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007ffff3735bf3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffed36d700 (LWP 33098)):
#0  0x00007ffff372b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c25f38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bd6c03 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7aa21a8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7c00511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3207422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3735bf3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffedb6e700 (LWP 33097)):
#0  0x00007ffff372b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c25f38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bd7221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7bd7272 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7c00511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff3207422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff3735bf3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffee2c59c0 (LWP 33093)):
#0  0x00007ffff38956aa in XKeysymToKeycode () at /usr/lib/libX11.so.6
#1  0x000055555575b2f1 in game_hub_utils_gamepad_emit_key_event (key_code=65363, press=1) at ../src/utils/Gamepad.vala:263
#2  0x0000555555759114 in game_hub_utils_gamepad_button_emit_key_event (self=0x5555653c1db0, press=1) at ../src/utils/Gamepad.vala:142
#3  0x00005555556a735c in game_hub_ui_views_games_view_games_view_on_gamepad_button (self=0x555565c68370, btn=547, press=1) at ../src/ui/views/GamesView/GamesView.vala:880
#4  0x00005555556a714d in game_hub_ui_views_games_view_games_view_on_gamepad_button_press_event (self=0x555565c68370, device=0x555565c8e9d0, e=0x555567344500) at ../src/ui/views/GamesView/GamesView.vala:865
#5  0x00005555556a6a32 in _game_hub_ui_views_games_view_games_view_on_gamepad_button_press_event_manette_device_button_press_event (_sender=0x555565c8e9d0, event=0x555567344500, self=0x555565c68370) at ../src/ui/views/GamesView/GamesView.vala:846
#6  0x00007ffff7cc2052 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff7cea685 in  () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7cde41d in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff7cde980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff394c388 in  () at /usr/lib/libmanette-0.2.so.0
#11 0x00007ffff7bd8340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff7c25fa9 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff7bd7221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7a6cc9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#15 0x000055555556db14 in game_hub_application_main (args=0x7fffffffe158, args_length1=2) at ../src/app.vala:242
#16 0x000055555556db6d in main (argc=2, argv=0x7fffffffe158) at ../src/app.vala:226

```

</details>

**Comment by tkashkin** [comment]
Controller currently only works on X11. GameHub translates controller buttons into X key events using XTest.
_(Yes, it's a bad hack, but I'm not sure if there's a better solution that doesn't require to reimplement standard keyboard behavior for each GTK widget. Maybe there's a way to simulate GTK events directly)_

Disable controller support in settings if you are using Wayland since it wouldn't do anything even if it wasn't crashing.

I'll try to simulate GTK events instead of keypresses or at least check if it's running under X11 before trying to emit an event.
