### ISSUE TITLE
Gamehub Hangs and doesn't display library any more

### ISSUE THREAD

**Issue by jtrv** [tkashkin/GameHub#656]
###### Steps to reproduce
Run `gamehub --debug` from terminal
Click skip because I can't authenticate Humble Bundle :/
App hangs for about 1 minute.
See that my library is gone.

Update: Now it looks like my steam and gog library are gone but some of my itch.io library remains.

###### Version and environment

```
- GameHub
    Version: 0.16.3-9952b8f-makepkg
    Branch:  makepkg
    Commit:  9952b8f2633e18ca32bec3762ecfe8589bee7593
- Environment
    Distro:  Arch Linux
    DE:      unknown
    GTK:     3.24.34
    Themes:  Materia-dark-compact | breeze-dark
```

###### GDB log

<details>
<summary>GDB log</summary>

```
[INFO]   Restarting with GDB
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[DEBUG]  [Database.migrate] Latest db version: 11, current: 11
[Detaching after fork from child process 128355]
[Detaching after fork from child process 128356]
[Detaching after fork from child process 128357]
[Detaching after fork from child process 128358]
[INFO]   - GameHub
[INFO]       Version: 0.16.3-9952b8f-makepkg
[INFO]       Branch:  makepkg
[INFO]       Commit:  9952b8f2633e18ca32bec3762ecfe8589bee7593
[INFO]   - Environment
[Detaching after fork from child process 128359]
[INFO]       Distro:  Arch Linux
[INFO]       DE:      unknown
[INFO]       GTK:     3.24.34
[INFO]       Themes:  Materia-dark-compact | breeze-dark
[Detaching after fork from child process 128380]
[Detaching after fork from child process 128381]
[Detaching after fork from child process 128403]
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[INFO]   [ButlerClient: log] Fetching fresh data...
[INFO]   [ButlerClient: log] Fetching page 1
[INFO]   [ButlerClient: log] Fetching page 2
[INFO]   [ButlerClient: log] Waited 99.360974ms for fetch (non-shared)
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'node != NULL' failed
[DEBUG]  [GOG] Loading games: page 1 of 1
^C
Thread 1 "com.github.tkas" received signal SIGINT, Interrupt.
0x00007ffff39ace9f in poll () from /usr/lib/libc.so.6

Thread 35 (Thread 0x7fffa2ffd6c0 (LWP 129391) "pool-com.github"):
#0  0x00007ffff39b256d in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff7c1c063 in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b9a8d3 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b9aa77 in g_async_queue_timeout_pop () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7bfe486 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7bfb405 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff393878d in  () at /usr/lib/libc.so.6
#7  0x00007ffff39b98e4 in clone () at /usr/lib/libc.so.6

Thread 20 (Thread 0x7fffe56f56c0 (LWP 128378) "threaded-ml"):
#0  0x00007ffff39ace9f in poll () at /usr/lib/libc.so.6
#1  0x00007fffe4d2d8c7 in  () at /usr/lib/libpulse.so.0
#2  0x00007fffe4d1746c in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fffe4d2142c in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fffe4d214e1 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fffe4d31c02 in  () at /usr/lib/libpulse.so.0
#6  0x00007fffe4ccdc47 in  () at /usr/lib/pulseaudio/libpulsecommon-16.1.so
#7  0x00007ffff393878d in  () at /usr/lib/libc.so.6
#8  0x00007ffff39b98e4 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe7fff6c0 (LWP 128354) "dconf worker"):
#0  0x00007ffff39ace9f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c21f68 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bc9392 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffec84febe in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff7bfb405 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff393878d in  () at /usr/lib/libc.so.6
#6  0x00007ffff39b98e4 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffed0ee6c0 (LWP 128308) "gdbus"):
#0  0x00007ffff39ace9f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c21f68 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bcb1cf in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7a89acc in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7bfb405 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff393878d in  () at /usr/lib/libc.so.6
#6  0x00007ffff39b98e4 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffed8ef6c0 (LWP 128307) "gmain"):
#0  0x00007ffff39ace9f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c21f68 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bc9392 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7bc93e2 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7bfb405 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff393878d in  () at /usr/lib/libc.so.6
#6  0x00007ffff39b98e4 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffedd1efc0 (LWP 128281) "com.github.tkas"):
#0  0x00007ffff39ace9f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c21f68 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7bc9392 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7a5330e in g_application_run () at /usr/lib/libgio-2.0.so.0
#4  0x000055555559521a in game_hub_application_main (args_length1=2, args=0x7fffffffd558) at ../src/app.vala:242
#5  main (argc=2, argv=0x7fffffffd558) at ../src/app.vala:226
```

</details>

**Comment by jtrv** [comment]
It looks like this was a false alarm. My filters appeared to be changed when viewing my library. I'm not sure if it was caused by an update or what but I've fixed the filters and can see the rest of my library, my apologies for the false alarm.
