### ISSUE TITLE
when choose "skip" at the main menu , then the gamehub crashes everytime

### ISSUE THREAD

**Issue by kamikaze211** [tkashkin/GameHub#673]
###### Version and environment

```
$ com.github.tkashkin.gamehub -v
- GameHub
    Version: 0.16.3-9327885-makepkg
    Branch:  makepkg
    Commit:  9327885393f022fd1cccb219a19c0f87ae5e0f5a
- Environment
    Distro:  Arch Linux
    DE:      KDE
    GTK:     3.24.36

```

###### GDB log

<details>
<summary>GDB log</summary>

```
com.github.tkashkin.gamehub --gdb
[INFO]   Restarting with GDB

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[DEBUG]  [Database.migrate] Latest db version: 11, current: 11
[Detaching after fork from child process 51900]
[Detaching after fork from child process 51901]
[Detaching after fork from child process 51902]
[WARN]   [AppInfoVDF] Error reading `/home/zzy/.steam/steam/appcache/appinfo.vdf`: Unknown node type: 0x85 (at 77)
[Detaching after fork from child process 51903]
[INFO]   - GameHub
[INFO]       Version: 0.16.3-9327885-makepkg
[INFO]       Branch:  makepkg
[INFO]       Commit:  9327885393f022fd1cccb219a19c0f87ae5e0f5a
[INFO]   - Environment
[Detaching after fork from child process 51904]
[INFO]       Distro:  Arch Linux
[INFO]       DE:      KDE
[INFO]       GTK:     3.24.36
[INFO]       Themes:  Layan-Light | Tela-pink
[Detaching after vfork from child process 51933]
[DEBUG]  Name com.canonical.AppMenu.Registrar does not exist on the session bus
[Detaching after vfork from child process 51935]
[DEBUG]  [fcitx-connection] _fcitx_connection_create_ic
[DEBUG]  [Gamepad] 'Sony Interactive Entertainment Wireless Controller' connected
[DEBUG]  [fcitx-connection] _fcitx_connection_connection_finished

Thread 1 "com.github.tkas" received signal SIGSEGV, Segmentation fault.
0x00007ffff340e35d in ?? () from /usr/lib/libc.so.6

Thread 39 (Thread 0x7fffad7fe6c0 (LWP 51954) "pool-com.github"):
#0  0x00007ffff33b80dd in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff7b96450 in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7af8a57 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b6850b in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 38 (Thread 0x7fffadfff6c0 (LWP 51953) "pool-com.github"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7b9960f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b30b12 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffcbedbbeb in  () at /usr/lib/gio/modules/libgiognutls.so
#4  0x00007ffff6bb3b01 in  () at /usr/lib/libsoup-2.4.so.1
#5  0x00007ffff6bbc323 in  () at /usr/lib/libsoup-2.4.so.1
#6  0x00007ffff6bbca15 in  () at /usr/lib/libsoup-2.4.so.1
#7  0x000055555576b99e in game_hub_utils_parser_load_remote_file (url=0x7fffa8063330 "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=8B10B604CAC6AC90F57AACE025DD904C&steamid=76561198287628810&format=json&include_appinfo=1&include_played_free_games=1", method=0x5555557a3046 "GET", auth=0x0, headers=0x0, data=0x0, status=0x7fffadffe1a8) at ../src/utils/Parser.vala:87
#8  0x000055555576c7f5 in game_hub_utils_parser_parse_remote_json_file (url=0x7fffa8063330 "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=8B10B604CAC6AC90F57AACE025DD904C&steamid=76561198287628810&format=json&include_appinfo=1&include_played_free_games=1", method=0x5555557a3046 "GET", auth=0x0, headers=0x0, data=0x0, status=0x0) at ../src/utils/Parser.vala:140
#9  0x00005555555cab7c in __lambda10_ (_data12_=0x555556bc0300) at ../src/data/sources/steam/Steam.vala:259
#10 0x00005555555cb260 in ___lambda10__game_hub_utils_future (self=0x555556bc0300) at ../src/data/sources/steam/Steam.vala:229
#11 0x0000555555749d09 in game_hub_utils_worker_run (self=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at ../src/utils/Utils.vala:47
#12 0x00005555557504c1 in ____lambda8_ (w=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at ../src/utils/Utils.vala:328
#13 0x00005555557504fe in _____lambda8__gfunc (data=0x555556bc0340, self=0x0) at ../src/utils/Utils.vala:328
#14 0x00007ffff7b684b3 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#17 0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 37 (Thread 0x7fffe14f96c0 (LWP 51952) "pool-com.github"):
#0  0x00007ffff33b80dd in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff7b96450 in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7af8a57 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b6850b in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 36 (Thread 0x7fffc8fff6c0 (LWP 51951) "pool-com.github"):
#0  0x00007ffff3384db5 in clock_nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff3389987 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7b5daf2 in g_usleep () at /usr/lib/libglib-2.0.so.0
#3  0x00005555556dd939 in __lambda395_ (self=0x55555659c3a0) at ../src/ui/views/GamesView/GamesView.vala:919
#4  0x00005555556dd982 in ___lambda395__game_hub_utils_future (self=0x55555659c3a0) at ../src/ui/views/GamesView/GamesView.vala:911
#5  0x0000555555749d09 in game_hub_utils_worker_run (self=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at ../src/utils/Utils.vala:47
#6  0x00005555557504c1 in ____lambda8_ (w=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at ../src/utils/Utils.vala:328
#7  0x00005555557504fe in _____lambda8__gfunc (data=0x555556bc0180, self=0x0) at ../src/utils/Utils.vala:328
#8  0x00007ffff7b684b3 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#11 0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 33 (Thread 0x7fffcb5ff6c0 (LWP 51947) "pool-com.github"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007ffff795e2d6 in g_socket_condition_timed_wait () at /usr/lib/libgio-2.0.so.0
#2  0x00007ffff795f064 in  () at /usr/lib/libgio-2.0.so.0
#3  0x00007ffff79332cf in g_input_stream_read () at /usr/lib/libgio-2.0.so.0
#4  0x00007fffcbed696d in  () at /usr/lib/gio/modules/libgiognutls.so
#5  0x00007fffc038037a in  () at /usr/lib/libgnutls.so.30
#6  0x00007fffc0238857 in  () at /usr/lib/libgnutls.so.30
#7  0x00007fffc0243f4c in  () at /usr/lib/libgnutls.so.30
#8  0x00007fffc02492ff in  () at /usr/lib/libgnutls.so.30
#9  0x00007fffc024fa27 in gnutls_handshake () at /usr/lib/libgnutls.so.30
#10 0x00007fffcbed6dbe in  () at /usr/lib/gio/modules/libgiognutls.so
#11 0x00007fffcbedb754 in  () at /usr/lib/gio/modules/libgiognutls.so
#12 0x00007ffff796f0b0 in  () at /usr/lib/libgio-2.0.so.0
#13 0x00007ffff7b684b3 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#16 0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 30 (Thread 0x7fffca9ff6c0 (LWP 51937) "threaded-ml"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007fffc82986c7 in  () at /usr/lib/libpulse.so.0
#2  0x00007fffc8286e6c in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fffc828cf4c in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fffc828d001 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fffc829d6e2 in  () at /usr/lib/libpulse.so.0
#6  0x00007fffc823a187 in  () at /usr/lib/pulseaudio/libpulsecommon-16.1.so
#7  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#8  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffe0cf86c0 (LWP 51908) "pool-com.github"):
#0  0x00007ffff33b80dd in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff7b96450 in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7af8a57 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b6850b in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe1cfa6c0 (LWP 51898) "dconf worker"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7b9960f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b30b12 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffe422dfde in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffe25fe6c0 (LWP 51897) "gdbus"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7b9960f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b35eef in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff79ded1c in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe2dff6c0 (LWP 51896) "gmain"):
#0  0x00007ffff33b29df in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7b9960f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7b30b12 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7b36322 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7b65fd5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff333dbb5 in  () at /usr/lib/libc.so.6
#6  0x00007ffff33bfd90 in  () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffed628080 (LWP 51893) "com.github.tkas"):
#0  0x00007ffff340e35d in  () at /usr/lib/libc.so.6
#1  0x00007ffff330fe34 in  () at /usr/lib/libc.so.6
#2  0x00007ffff3310487 in  () at /usr/lib/libc.so.6
#3  0x00007ffff33322a5 in  () at /usr/lib/libc.so.6
#4  0x00007ffff7b8ccc3 in g_vasprintf () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7b5bbd2 in g_strdup_vprintf () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff7b5bca6 in g_strdup_printf () at /usr/lib/libglib-2.0.so.0
#7  0x00005555556d8971 in game_hub_ui_views_games_view_games_view_update_view (self=0x55555659c3a0) at ../src/ui/views/GamesView/GamesView.vala:553
#8  0x00005555556ddeb6 in _game_hub_ui_views_games_view_games_view_update_view_game_hub_data_adapters_games_adapter_cache_loaded (_sender=0x555556b95910, self=0x55555659c3a0) at ../src/ui/views/GamesView/GamesView.vala:235
#9  0x00007ffff7c4033e in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff7c79897 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff7c68152 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff7c687dc in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x000055555566ab8c in __lambda340_ (_data43_=0x555555abe580) at ../src/data/adapters/GamesAdapter.vala:235
#14 0x000055555566abd3 in ___lambda340__gsource_func (self=0x555555abe580) at /usr/src/debug/gamehub/GameHub/build/GamesAdapter.c:2327
#15 0x00007ffff7b371bb in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff7b996a9 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff7b30b12 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff79a0b1e in g_application_run () at /usr/lib/libgio-2.0.so.0
#19 0x0000555555596c08 in game_hub_application_main (args=0x7fffffffe318, args_length1=2) at ../src/app.vala:242
#20 0x0000555555596c65 in main (argc=2, argv=0x7fffffffe318) at ../src/app.vala:226

```

</details>

**Comment by DartMitai** [comment]
I have it turned off at the beginning of the installation of any game, even without pressing the skip button
