### ISSUE TITLE
set_button_image_get_info_cb: assertion failed: (cancellable == data->button_data->cancellable)

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#76]
In rare cases, selecting an executable for a game, can crash the program:

```
Gtk:ERROR:gtkpathbar.c:1343:set_button_image_get_info_cb: assertion failed: (cancellable == data->button_data->cancellable)

Thread 1 "com.github.tkas" received signal SIGABRT, Aborted.
0x00007ffff321fd7f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff321fd7f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff320a672 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff7948048 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff79a13cc in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7294cc1 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff71ee77c in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff66c83b4 in  () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff66c83e9 in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff7979b49 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7979f59 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff797a272 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff71b930f in gtk_dialog_run () at /usr/lib/libgtk-3.so.0
#12 0x0000555555567219 in game_hub_data_game_real_choose_executable (self=0x7fffc80fcdf0, update=1)
    at /home/g/Games/GameHub-dev/src/data/Game.vala:202
#13 0x000055555556749d in game_hub_data_game_choose_executable (self=0x7fffc80fcdf0, update=1)
    at /home/g/Games/GameHub-dev/src/data/Game.vala:166
#14 0x000055555556c5c5 in game_hub_data_game_installer_install_co (_data_=0x555580bfdd30)
    at /home/g/Games/GameHub-dev/src/data/Game.vala:395
#15 0x0000555555569a74 in game_hub_data_game_installer_install_ready (source_object=0x5555851298a0, _res_=0x555588dbb020, _user_data_=0x555580bfdd30) at /home/g/Games/GameHub-dev/src/data/Game.vala:297
#16 0x00007ffff66c83b4 in  () at /usr/lib/libgio-2.0.so.0
#17 0x00007ffff66c83e9 in  () at /usr/lib/libgio-2.0.so.0
#18 0x00007ffff7979b49 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff7979f59 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff7979fee in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff66df19e in g_application_run () at /usr/lib/libgio-2.0.so.0
#22 0x0000555555564e20 in game_hub_application_main (args=0x7fffffffe818, args_length1=1) at /home/g/Games/GameHub-dev/src/app.vala:65
#23 0x0000555555564e77 in main (argc=1, argv=0x7fffffffe818) at /home/g/Games/GameHub-dev/src/app.vala:56
```

**Comment by tkashkin** [comment]
It seems to be either GTK bug or your DE/file manager bug (e.g. elementary OS uses custom module to override GTK file/folder selection dialogs and it logs some errors occasinally).
